project_name: dotfiles

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: dotfiles
    binary: dotfiles
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - Brewfile.template
      - Brewfile.example
      - config/**/*
      - presets/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: dotfiles
    description: "Modern dotfiles management system built in Go"
    homepage: "https://github.com/{{ .Env.GITHUB_USERNAME }}/{{ .ProjectName }}"
    license: "MIT"
    folder: Formula
    dependencies:
      - gnu-stow
    install: |
      bin.install "dotfiles"
    test: |
      system "#{bin}/dotfiles", "--version"

nfpms:
  - id: packages
    package_name: dotfiles
    file_name_template: '{{ .ConventionalFileName }}'
    vendor: "{{ .Env.GITHUB_USERNAME }}"
    homepage: "https://github.com/{{ .Env.GITHUB_USERNAME }}/{{ .ProjectName }}"
    maintainer: "{{ .Env.GITHUB_USERNAME }} <{{ .Env.GITHUB_EMAIL }}>"
    description: "Modern dotfiles management system built in Go"
    license: "MIT"
    formats:
      - deb
      - rpm
    dependencies:
      - stow

release:
  github:
    owner: "{{ .Env.GITHUB_USERNAME }}"
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Version }}"
  header: |
    ## What's New

    {{ .Version }} brings exciting new features and improvements to your dotfiles management experience.
  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install {{ .Env.GITHUB_USERNAME }}/tap/dotfiles
    ```

    ### Direct Download
    Download the binary for your platform from the [releases page](https://github.com/{{ .Env.GITHUB_USERNAME }}/{{ .ProjectName }}/releases).

    ### Go Install
    ```bash
    go install github.com/{{ .Env.GITHUB_USERNAME }}/{{ .ProjectName }}@latest
    ```